name: "Restore any Typst package cache"
description: "Configures the caching for Typst packages"
outputs:
  cache-hit:
    description: "Is there a cache restored ?"
    value: ${{ steps.cache-typst-restore.outputs.cache-hit }}
  cache-key:
    description: "Key of the cache considered"
    value: ${{ steps.cache-typst-restore.outputs.cache-primary-key }}
  cache-path:
    description: "where is the packages cache for typst ?"
    value: ${{ steps.cache-typst-path.outputs.TYPST_CACHE }}

runs:
  using: "composite"
  steps:
    - name: Typst Cache path
      id: cache-typst-path
      run: |
        case $RUNNER_OS in
          "Linux")
              echo "TYPST_CACHE=${XDG_CACHE_HOME:-~/.cache}/typst/packages/" >> $GITHUB_ENV
              ;;
          "macOS")
              echo "TYPST_CACHE=~/Library/Caches/typst/packages/" >> $GITHUB_ENV
              ;;
          "Windows")
              echo "TYPST_CACHE=$LOCALAPPDATA/typst/packages/" >> $GITHUB_ENV
              ;;
            *)
              echo "$RUNNER_OS not supported"
              exit 1
              ;;
        esac
        echo "TYPST_CACHE=${TYPST_CACHE}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache Typst package folder
      id: cache-typst-restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ env.TYPST_CACHE }}
        key: ${{ runner.os }}-typst-1
